version: '3'
services:
  db:
    image: wqp_biodata_db
    build:
      context: .
    networks:
      wqp:
        ipv4_address: ${DB_IPV4}
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${BIODATA_DATABASE_NAME}
    ports:
      - ${DB_PORT}:5432
    container_name: ${BIODATA_DATABASE_ADDRESS}

  liquibase:
    image: wqp_biodata_liquibase
    build:
      context: ./liquibase
      args:
        - LIQUIBASE_VERSION=${LIQUIBASE_VERSION}
        - A_JDBC_JAR=${JDBC_JAR}
    networks:
      wqp:
        ipv4_address: ${LIQUIBASE_IPV4}
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - BIODATA_DATABASE_ADDRESS=${BIODATA_DATABASE_ADDRESS}
      - BIODATA_DATABASE_NAME=${BIODATA_DATABASE_NAME}
      - BIODATA_DB_OWNER_USERNAME=${BIODATA_DB_OWNER_USERNAME}
      - BIODATA_DB_OWNER_PASSWORD=${BIODATA_DB_OWNER_PASSWORD}
      - BIODATA_SCHEMA_NAME=${BIODATA_SCHEMA_NAME}
      - BIODATA_SCHEMA_OWNER_USERNAME=${BIODATA_SCHEMA_OWNER_USERNAME}
      - BIODATA_SCHEMA_OWNER_PASSWORD=${BIODATA_SCHEMA_OWNER_PASSWORD}
      - WQP_SCHEMA_NAME=${WQP_SCHEMA_NAME}
      - WQP_SCHEMA_OWNER_USERNAME=${WQP_SCHEMA_OWNER_USERNAME}
      - WQP_SCHEMA_OWNER_PASSWORD=${WQP_SCHEMA_OWNER_PASSWORD}
    volumes:
      - ./liquibase/changeLogs:/home/java/workspace/biodata
      - ./liquibase/scripts:/docker-entrypoint-initdb.d
    container_name: biodata_liquibase

networks:
  wqp:
    external:
      name: ${LOCAL_NETWORK_NAME}
